name: Deploy Idealist to Algolia

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_INDEX_NAME: "volunteer_idealist_Goodacts"  # if you kept it as a secret
      CRON_ENABLED: true
      WAIT_SECONDS: 0.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Idealist Importer
        run: |
          export IDEALIST_AUTH_TOKEN="d8e1323d728601a6f9d9b1fc4a162060"
          export ALGOLIA_APP_ID="92CHORLCOD"
          export ALGOLIA_API_KEY="680cd7887ae9b0e30f9734042b7a7abd"
          python -m importer.cron